const BankRDRates: Record<string, any> = {
  SBI: {
    bankCode: "SBI",
    bankName: "State Bank of India",
    compounding: "quarterly",
    rates: [
      {
        type: "regular",
        minMonths: 12,
        maxMonths: 23,
        general: 6.8,
        senior: 7.3,
        label: "1 year to less than 2 years",
      },
      {
        type: "regular",
        minMonths: 24,
        maxMonths: 35,
        general: 7.0,
        senior: 7.5,
        label: "2 years to less than 3 years",
      },
      {
        type: "regular",
        minMonths: 36,
        maxMonths: 59,
        general: 6.75,
        senior: 7.25,
        label: "3 years to less than 5 years",
      },
      {
        type: "regular",
        minMonths: 60,
        maxMonths: 120,
        general: 6.5,
        senior: 7.5,
        label: "5 years and up to 10 years",
      },
    ],
  },
  HDFC:{
    bankCode: "HDFC",
    bankName: "HDFC Name",
    compounding: "quarterly",
    rates: [
      {
        type: "regular",
        minMonths: 6,
        maxMonths: 6,
        general: 4.25,
        senior: 4.75,
        label: "6 months",
      },
      {
        type: "regular",
        minMonths: 9,
        maxMonths: 9,
        general: 5.50,
        senior: 6.00,
        label: "9 months",
      },
      {
        type: "regular",
        minMonths: 12,
        maxMonths: 12,
        general: 6.25,
        senior: 6.75,
        label: "12 months",
      },
      {
        type: "regular",
        minMonths: 15,
        maxMonths: 15,
        general: 6.35,
        senior: 6.85,
        label: "15 months",
      },
      {
        type: "regular",
        minMonths: 18,
        maxMonths: 36,
        general: 6.45,
        senior: 6.95,
        label: "18 months to 36 months",
      },
      {
        type: "regular",
        minMonths: 39,
        maxMonths: 60,
        general: 6.40,
        senior: 6.90,
        label: "39 months to 60 months",
      },
      {
        type: "regular",
        minMonths: 63,
        maxMonths: 120,
        general: 6.15,
        senior: 6.65,
        label: "Above 60 months",
      },
    ],
  }
};
export default BankRDRates;
