const Banks = [
  { code: "SBI", name: "State Bank of India" },
  { code: "PNB", name: "Punjab National Bank" },
  { code: "BOB", name: "Bank of Baroda" },
  { code: "CANARA", name: "Canara Bank" },
  { code: "UNION", name: "Union Bank of India" },
  { code: "INDIAN", name: "Indian Bank" },
  { code: "BOI", name: "Bank of India" },
  { code: "CBI", name: "Central Bank of India" },
  { code: "IOB", name: "Indian Overseas Bank" },
  { code: "UCO", name: "UCO Bank" },
  { code: "BOM", name: "Bank of Maharashtra" },
  { code: "PSB", name: "Punjab & Sind Bank" },
  { code: "HDFC", name: "HDFC Bank" },
  { code: "ICICI", name: "ICICI Bank" },
  { code: "AXIS", name: "Axis Bank" },
  { code: "KOTAK", name: "Kotak Mahindra Bank" },
  { code: "IDFC", name: "IDFC First Bank" },
  { code: "INDUSIND", name: "IndusInd Bank" },
  { code: "YES", name: "Yes Bank" },
  { code: "FEDERAL", name: "Federal Bank" },
  { code: "RBL", name: "RBL Bank" },
  { code: "BANDHAN", name: "Bandhan Bank" },
  { code: "CUB", name: "City Union Bank" },
  { code: "DCB", name: "DCB Bank" },
  { code: "KVB", name: "Karur Vysya Bank" },
  { code: "SIB", name: "South Indian Bank" },
  { code: "AU", name: "AU Small Finance Bank" },
  { code: "UJJIVAN", name: "Ujjivan Small Finance Bank" },
  { code: "EQUITAS", name: "Equitas Small Finance Bank" },
  { code: "JANA", name: "Jana Small Finance Bank" },
  { code: "ESAF", name: "ESAF Small Finance Bank" },
  { code: "SURYODAY", name: "Suryoday Small Finance Bank" },
  { code: "UTKARSH", name: "Utkarsh Small Finance Bank" },
  { code: "SHIVALIK", name: "Shivalik Small Finance Bank" },
];
export default Banks;